import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import getData from "@/lib/query";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const revalidate = 0;

export default async function RootLayout({ children }) {
  const navbarQuery = await getData("navigation");
  const navbarData = navbarQuery.props.data;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar navigation={navbarData} />

        {children}
      </body>
    </html>
  );
}
